#!/usr/bin/env python3
"""
Test script to validate the word frequency output.
"""
import re
import sys
from collections import Counter


def read_output():
    """Read the output file generated by the agent."""
    try:
        with open('/app/output.txt', 'r') as f:
            lines = f.read().strip().split('\n')
        return [line.strip() for line in lines if line.strip()]
    except FileNotFoundError:
        print("ERROR: /app/output.txt not found")
        sys.exit(1)


def read_input():
    """Read the input file and compute expected results."""
    try:
        with open('/app/input.txt', 'r') as f:
            text = f.read()
    except FileNotFoundError:
        print("ERROR: /app/input.txt not found")
        sys.exit(1)
    
    # Process text
    text = text.lower()
    words = re.findall(r'[a-z]+', text)
    word_counts = Counter(words)
    top_10 = word_counts.most_common(10)
    
    return [word for word, count in top_10]


def main():
    """Main test function."""
    output_words = read_output()
    expected_words = read_input()
    
    # Check if we have exactly 10 words
    if len(output_words) != 10:
        print(f"ERROR: Expected 10 words, got {len(output_words)}")
        sys.exit(1)
    
    # Check if the words match the expected top 10
    if output_words != expected_words:
        print("ERROR: Word list does not match expected output")
        print(f"Expected: {expected_words}")
        print(f"Got: {output_words}")
        sys.exit(1)
    
    # Check for any non-alphabetic characters or empty lines
    for word in output_words:
        if not word.isalpha() or not word.islower():
            print(f"ERROR: Invalid word format: '{word}'")
            sys.exit(1)
    
    print("SUCCESS: All tests passed!")
    sys.exit(0)


if __name__ == "__main__":
    main()
